#!/usr/bin/env python3
"""Generate portable agent adapters and the Codex marketplace package."""

from __future__ import annotations

import argparse
import filecmp
import json
import shutil
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
ROLE_FILE = ROOT / "roles" / "roles.json"
GENERATED_HEADER = "<!-- Generated by scripts/generate_adapters.py; edit roles/roles.json instead. -->"


def load_roles() -> list[dict]:
    data = json.loads(ROLE_FILE.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1 or not isinstance(data.get("roles"), list):
        raise SystemExit(f"Unsupported role registry: {ROLE_FILE}")
    return data["roles"]


def render_markdown_agent(role: dict) -> str:
    lines = [
        "---",
        f"name: {role['id']}",
        f"description: {role['description']}",
        "---",
        GENERATED_HEADER,
        "",
        f"Use the installed `{role['id']}` Agent Skill as your operating procedure.",
        role["instructions"],
        "Work only from the brief, acceptance criteria, assigned paths, and supplied artifacts.",
    ]
    if role.get("read_only"):
        lines.append("Remain independent: do not modify project files and do not use the maker's hidden reasoning.")
    else:
        lines.append("Return changed paths, verification performed, evidence, and known limitations.")
    return "\n".join(lines) + "\n"


def kimi_role_map(roles: list[dict]) -> dict:
    mapping = {}
    for role in roles:
        if role["kind"] == "maker":
            agent = "coder"
        elif role["kind"] in {"reviewer", "coordinator"}:
            agent = "explore"
        else:
            agent = "coder"
        mapping[role["id"]] = {
            "built_in_agent": agent,
            "instructions": role["instructions"],
            "read_only": role.get("read_only", False),
        }
    return {"schema_version": 1, "roles": mapping}


def sync_tree(source: Path, destination: Path) -> None:
    if destination.exists():
        shutil.rmtree(destination)
    shutil.copytree(source, destination, ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))


def generate(root: Path) -> None:
    roles = load_roles()
    agents = root / "agents"
    agents.mkdir(parents=True, exist_ok=True)
    expected = set()
    for role in roles:
        path = agents / f"{role['id']}.md"
        path.write_text(render_markdown_agent(role), encoding="utf-8")
        expected.add(path.name)
    for path in agents.glob("*.md"):
        if path.name not in expected:
            path.unlink()

    kimi_dir = root / "adapters" / "kimi"
    kimi_dir.mkdir(parents=True, exist_ok=True)
    (kimi_dir / "role-map.json").write_text(
        json.dumps(kimi_role_map(roles), indent=2) + "\n", encoding="utf-8"
    )

    package = root / "plugins" / "godot-gamestudio"
    package.mkdir(parents=True, exist_ok=True)
    sync_tree(root / "skills", package / "skills")
    if (package / "scripts").exists():
        shutil.rmtree(package / "scripts")
    (package / "scripts").mkdir(parents=True)
    for name in ("install_agents.py", "select_team.py", "studio_state.py"):
        shutil.copy2(root / "scripts" / name, package / "scripts" / name)
    sync_tree(root / "roles", package / "roles")
    sync_tree(root / ".codex-plugin", package / ".codex-plugin")


def trees_equal(left: Path, right: Path) -> bool:
    comparison = filecmp.dircmp(left, right)
    if comparison.left_only or comparison.right_only or comparison.funny_files:
        return False
    if any(not filecmp.cmp(left / name, right / name, shallow=False) for name in comparison.common_files):
        return False
    return all(trees_equal(left / name, right / name) for name in comparison.common_dirs)


def check() -> None:
    with tempfile.TemporaryDirectory() as temp:
        candidate = Path(temp) / "repo"
        shutil.copytree(ROOT, candidate, ignore=shutil.ignore_patterns(".git", "dist", "__pycache__", "*.pyc"))
        generate(candidate)
        for relative in ("agents", "adapters/kimi", "plugins/godot-gamestudio"):
            if not trees_equal(ROOT / relative, candidate / relative):
                raise SystemExit(f"Generated adapter drift detected in {relative}; run scripts/generate_adapters.py")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when committed generated files are stale")
    args = parser.parse_args()
    if args.check:
        check()
    else:
        generate(ROOT)


if __name__ == "__main__":
    main()
